### ISSUE TITLE
Reaching out phisycal source files in the system

### ISSUE THREAD

**Issue by mlstoppa** [barrettotte/vscode-ibmi-languages#50]
Hi,
I really appreciate your work, because I would like to edit IBM i sources from VSC, so I am sorry to ask a question that may be silly, but I can't answer it on my own.
I would like to edit sources which are not in the IFS, but in IBM I operating system.
I tried to open such a mapped folder:
\\myip\root\QSYS.LIB\MYLIB.LIB\QILESRC.FILE
and it works, meaning I can see the list of all source members inside it.
But when I open a single member to edit it, it is not translated into the correct code page, so all I see is a long list of useless characters.
How do you reach the IBM system through VSC?
Is there a different way to reach out source files in a library?
Thank you

**Comment by barrettotte** [comment]
Thanks for taking the time to ask, yeah that's the unfortunate part of using VS Code at the moment. In the older "library" method of file structures there's not a simple solution for it. 

I think a lot of it has to do with record lengths and EBCDIC encoding. This is actually a problem I'm trying to tackle in a side project I've been casually working on. In the next year I hope to complete a dotnet core project to provide a simple IBMi CLI to use with VS Code's terminal. Unfortunately, I don't have anything I can share at the moment. Using the IFS with VS Code is the only method of editing that I am aware of at the moment.

As a temporary workaround, I've used [CPYTOSTMF](https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_73/cl/cpytostmf.htm) and [CPYFRMSTMF](https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_73/cl/cpyfrmstmf.htm) in a workflow like this:

1. Copy source member to temporary file on IFS with ```CPYTOSTMF FROMMBR('QSYS.LIB/MYLIB.LIB/MYFILE.FILE/MYMBR.MBR') TOSTMF('/home/MYUSER/edit/MYMBR.RPGLE')```

2. Edit temporary IFS file using VS Code

3. Copy temporary file back to source member with ```CPYFRMSTMF FROMSTMF('/home/MYUSER/edit/MYMBR.RPGLE') TOMBR('QSYS.LIB/MYLIB.LIB/MYFILE.FILE/MYMBR.MBR') MBROPT(*REPLACE)```

However, this still requires the usage of the IFS and doesn't really give you a good solution for your situation.

Thanks for reaching out, I'm going to leave this issue open because I'm sure there are others that are wondering the same thing.

**Comment by mlstoppa** [comment]
Hi,
Thank you for answering.

Your proposal is the same I thought of, so I think I will end by using it. Only, can you compile from a source file in the IFS?

If it is of any interest to you, I know that at least one of two non-IBM IDE for RPG sources (ILEditor 2 by Liam Allan) uses SSH to read/write to native library files, but I'd like to work with only one editor, if possible. 

Thanks for keeping this topic open.

**Comment by barrettotte** [comment]
Yeah I tried out ILEditor (1) and ILEditor 2 for a bit, but I also like the "all in one" editor concept that VS Code promotes. I was really hoping ILEditor 2 was going to be a VS Code extension of some sort...

As far as compiling from the IFS, I started to learn the concepts from https://github.com/NielsLiisberg/RPG-vsCode-Getting-Started . This uses GNU Make as part of the build process. 

Personally, I don't like messing around with Make files very much so I opted to start using Bash scripts instead. Using Bash also allows you to skip over installing GNU Make and I find it a little more intuitive to work with.

Here are a couple example repos where I build entirely from the IFS:
- https://github.com/barrettotte/Anilist-IBMi/blob/master/makefile (using GNU Make approach)
- https://github.com/barrettotte/RPGLE-Twilio/blob/master/build.sh (using Bash script)

I have a gist of a "generic" build script, but it is far from perfect...I hope to revisit it in the future 
https://gist.github.com/barrettotte/278e1e97fc2ba23c7ad6366b0b4c8668 .

There are probably better methods out there somewhere for building. [Niels Liisberg](https://github.com/NielsLiisberg) and [Liam Barry](https://github.com/worksofliam) are the two people I've seen that share some interesting stuff revolving around development using the IFS

**Comment by mlstoppa** [comment]
Great suggestions. Thank you

**Comment by chrjorgensen** [comment]
A late but hopefully useful addition to this discussion... ;-)

You can easily compile from IFS - no need for copying to a traditional source file before compile.
Most compile commands have now a parameter SRCSTMF where you specify the streamfile in the IFS.
All RPG, COBOL, CL, CMD create commands have this.

If the CRT command does not have the SRCFILE parameter, you can use the excellent utility from Brian Garland called [CRTFRMSTMF](https://github.com/BrianGarland/CRTFRMSTMF). This allows compilation of DDS (DSPF, PF, LF), PNLGRP etc.

Once I started using the IFS and git on my IBM i source I never looked back. :-)

**Comment by barrettotte** [comment]
@chrjorgensen @mlstoppa Hello, it has been a while. Recently a new IBM i extension has been created at https://github.com/halcyon-tech/code-for-ibmi . 

This extension provides the ability to browse/edit source on the IFS or QSYS file systems, compile source, and more. Its still in development, but I feel that it is in a very good place right now.

**Comment by barrettotte** [comment]
closing since https://github.com/halcyon-tech/code-for-ibmi solves this issue.
