### ISSUE TITLE
Option to 'Show block nesting' for nested conditionals.

### ISSUE THREAD

**Issue by CraigMcloughlin** [barrettotte/vscode-ibmi-languages#61]
First off, thanks for making this VS extension. It's great to be able to get a good reading view on some RPG/LE/CL code without the need to download a IBM IDE.

I'm unsure if this is a feature request or potentially covered by another extension, but have you come across the ability to pair up rpg conditions. I'm often looking at code with a ton of nested 'if' statements:

![image](https://user-images.githubusercontent.com/18596216/107644896-f2773380-6c6f-11eb-9d0b-ad0929e2971d.png)

IBM IDEs such as WebSphere have a handy feature for 'show block nesting':

![image](https://user-images.githubusercontent.com/18596216/107645084-2c483a00-6c70-11eb-982b-07ec062e2ef5.png)

**Comment by barrettotte** [comment]
@CraigMcloughlin Yeah I find myself getting lost in those nested blocks a lot and would love to work on that feature.

I think I'm going to try to experiment using the same method that other languages use by matching up brackets, except this time use ```IF``` as start and ```ENDIF``` as end. If that works I can extend it to loops, subroutines, and procedures. I'll mention you on this issue with what happens.

If that doesn't work, then there's some decent challenges. I need to do some more reading up on it, but I think it would require some knowledge on Language Server Protocol (LSP) that I don't quite have yet. I talked about it a bit in https://github.com/barrettotte/vscode-ibmi-languages/issues/51. The major pain point is implementing enough of an RPG/RPGLE parser in order to tell where you are in the parse tree and report it back to VS Code for display/interaction.

This part is definitely not impossible, but it would take a good amount of time to learn and implement. I just need to wake up one morning with the itch to dive into it. Thanks for reporting!

**Comment by barrettotte** [comment]
@CraigMcloughlin Hello, I haven't quite gotten around to trying to fix this issue yet. But, it may be taken care of in the future by another extension.

I just wanted to pass on that a new IBM i VS Code extension has been developed at https://github.com/halcyon-tech/code-for-ibmi. It works together with this syntax highlighter to allow actual source editing on IBM i.

This extension provides the ability to browse/edit source on the IFS or QSYS file systems, compile source, and more. Its still in development, but I feel that it is in a very good place right now.

**Comment by CraigMcloughlin** [comment]
Hi @barrettotte ,  Thanks for the info - I'll definitely check it out :-)

**Comment by barrettotte** [comment]
@CraigMcloughlin Released in [v0.5.6](https://github.com/barrettotte/vscode-ibmi-languages/releases/tag/v0.5.6)

**Comment by barrettotte** [comment]
I should have added a screenshots so I didn't seem like I was crazy

![image](https://user-images.githubusercontent.com/15623775/109404569-6a628080-7935-11eb-806d-6a43eeff1933.png)

![image](https://user-images.githubusercontent.com/15623775/109404592-97169800-7935-11eb-8477-bdac2c2da69f.png)

These are pretty trivial examples, but feel free to open another issue if something seems wacky.
The only thing I couldn't get working was ```CASxx``` instructions, but I think its a small sacrifice
